### ISSUE TITLE
[バック] Github Actions

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/programing_quiz#116]
## **機能概要**

GitHub Actionsは、GitHubのCI/CD機能を提供するサービスです。これを利用して、コードがGitHubにプッシュされたり、プルリクエストが作成された際に、指定されたジョブ（ここではRSpecテスト）を自動で実行することができます。GitHub Actionsを活用することで、テストやデプロイの自動化を行い、コードの品質やデリバリーを効率的に管理できます。

---

## **ゴール**

1. **GitHub Actionsを使ってCIパイプラインを設定**し、`main`ブランチに対するコードのプッシュやプルリクエストが自動的にテストを実行するようにする。
2. **RSpecのテストを自動実行**し、GitHub Actions内でテスト結果を表示できるようにする。
3. **GitHub ActionsでCIプロセスの自動化**を実現し、テストの成功または失敗をリアルタイムで確認できるようにする。

---

#### **実装内容**

GitHub Actionsを使ってCIパイプラインを作成し、コードがプッシュされるたびに自動でRSpecテストを実行する設定を行います。

- **GitHub Actions設定ファイルの作成**
  - `.github/workflows/ci.yml`にCIパイプラインの設定を記述します。

**設定ファイル例**

```yaml
name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RSpec tests
      run: |
        bundle exec rspec
```

#### **要件**

- [ ] `main`ブランチにプッシュやプルリクエストが行われると、自動でRSpecテストが実行されるようにGitHub Actionsが設定される。
- [ ] テスト結果がGitHub Actionsのログに表示され、エラーが発生した場合には通知される。

---

#### **実装内容**

GitHub ActionsでRSpecテストを実行するためのジョブ設定を行い、テスト結果を確認します。

- **RSpecテストの実行**

```yaml
    - name: Run RSpec tests
      run: |
        bundle exec rspec
```

#### **要件**

- [ ] テストがGitHub Actionsで正常に実行され、結果が表示される。

---

#### **実装内容**

テストが成功した後、アプリケーションを自動でデプロイする設定を追加することも可能です（例えば、HerokuやAWSへのデプロイ）。

**デプロイ設定例（Heroku）**

```yaml
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/your-app.git
        git push heroku main
```

#### **要件**

- [ ] テストが成功した後、必要に応じて自動デプロイが行われるように設定される。

---
 参考文献

- [RailsプロジェクトにGitHub Actionsを導入する方法（Rspec, Rubocop）](https://qiita.com/JZ8xNeXY/items/fef7efb5eb9495b62faf)
